version: '3'
services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
    volumes:
      - ./www:/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php
    volumes:
      - ./www:/www
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql

